title: "100 Days of Data & Sports Challenge"
description: "ML Engineer & Data Scientist specializing in Sports Analytics"
url: "https://david-bazaldua.github.io"
baseurl: "/100-days-Data-Sports-Challenge"

theme: jekyll-theme-minimal
markdown: kramdown
highlighter: rouge

navigation:
  - title: Home
    url: /
  - title: Roadmap
    url: /roadmap/
  - title: Projects
    url: /projects/
  - title: Journal
    url: /journal/
  - title: Resources
    url: /resources/
  - title: About
    url: /about/

collections:
  projects:
    output: true
    permalink: /projects/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
